### ISSUE TITLE
OpenGL rendering

### ISSUE THREAD

**Issue by RummanUK** [tanjinbd/LiberationWar5#1]
Hi,

I have downloaded the code, have seen your resource folder. I have seen the Coverflow sections pull the OpenGL ES library, the execution is fast and efficient. I am just wondering can it be ported to iOS also?

I am planning to recode certain portion to Swift so that similar thing can be achieved on iOS.

**Comment by tanjinbd** [comment]
Yes, surely as the rendering is done with pixel and vectors. IT can be ported to any platform. 

Great, if you start porting it to Swift for IOS, let us collaborate together. Let me know if you need any assistance learning the code structure or any class/method

**Comment by RummanUK** [comment]
Sure, let us work together!

Also about Metro tile based interface, I have seen the live tiles is not working on my Emulator, is it device specific?

**Comment by tanjinbd** [comment]
Well, I have seen similar issue on few phones as tiles update method needs to be run in the background. Few phones/emulator restricts threaded classes running in the background. Will recode the sections to extend compatibility and support.

**Comment by RummanUK** [comment]
Moreover OpenGL ES 3.0 and 3.1 fixes all memory and crash related bugs, do you have any plan to upgrade to that version?

**Comment by tanjinbd** [comment]
I Agree, OpenGL ES 3.0 and 3.1 fixes all memory and crash related bugs and many performance optimizations but unfortunately upgrading to higher version will result the project purpose of Highest Possible compatibility with old Android device. Which demolishes the projects main vision of Archiving the very old Cover flow for all mobile devices.

Let us work on iOS version with Swift

**Comment by RummanUK** [comment]
Hi, I have started converting the project to iOS (using Native Swift for rendering), can you please share the details for Cover Flow rendering concept as general?

**Comment by tanjinbd** [comment]
In the project root folder, go to: src\com\gpit\bd\liberation

Following Android Libraries are used: 
view.animation.Transformation
android.graphics.Matrix

also check transformImageBitmap() class:
 if ( rotation < mMaxRotationAngle ) {
       float zoomAmount = (float) (mMaxZoom +  (rotation * 1.5));
       mCamera.translate(0.0f, 0.0f, zoomAmount);          
      } 

With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.

**Comment by bryantmero** [comment]
Hi Tanjin,

I have downloaded your project, happy to see simple OpenGL usage using Android libraries. @RummanUK can you please update me on the Swift version of the coverflow. Willing to learn and help!!

@tanjinbd , I have tried to run it on Android 12 but kind of getting choppy frame rate, any idea on this?

**Comment by RummanUK** [comment]
> In the project root folder, go to: src\com\gpit\bd\liberation
> 
> Following Android Libraries are used: view.animation.Transformation android.graphics.Matrix
> 
> also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }
> 
> With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.

Thanks, I am already started working on it. @bryantmero hope to upload to a branch when my beta version is ready

**Comment by bryantmero** [comment]
> > In the project root folder, go to: src\com\gpit\bd\liberation
> > Following Android Libraries are used: view.animation.Transformation android.graphics.Matrix
> > also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }
> > With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.
> 
> Thanks, I am already started working on it. @bryantmero hope to upload to a branch when my beta version is ready

I have already started some homework, this steps I am following for conversion to Swift (Metal Graphics)

o some OpenGL cleanup. Follow these steps:

1. Rename both occurrences of setupGL() to setupMetal().
2. Remove tearDownGL() and deinit() methods. With Metal, there’s no need for explicit cleanup like this.
3. Find and remove the whole extension GLKViewControllerDelegate, since this view controller is no longer a GLKViewController. Note that glkViewControllerUpdate contains the logic for spinning. This is useful, but for now, remove it.
4. Remove the following code from the top of setupMetal():

context = EAGLContext(api: .openGLES3)
EAGLContext.setCurrent(context)
    
if let view = self.view as? GLKView, let context = context {
  view.context = context
  delegate = self
}

5. Remove the following properties from the top of ViewController:

private var context: EAGLContext?
private var effect = GLKBaseEffect()
private var ebo = GLuint()
private var vbo = GLuint()
private var vao = GLuint()

Finally, at the top of the ViewController class declaration, add an outlet to a MTKView:

@IBOutlet weak var metalView: MTKView!

**Comment by bryantmero** [comment]
@tanjinbd can you please upload the PNG Graphic assets in High Res? I will use those in the iOS project

**Comment by tanjinbd** [comment]
> @tanjinbd can you please upload the PNG Graphic assets in High Res? I will use those in the iOS project

Hi Bryant, As requested I have uploaded High Res PNG assets:
Filename: [Asset_High_res.zip](https://github.com/tanjinbd/LiberationWar5/blob/main/Asset_High_res.zip)

**Comment by luismartinez03** [comment]
> > > In the project root folder, go to: src\com\gpit\bd\liberation
> > > Following Android Libraries are used: view.animation.Transformation android.graphics.Matrix
> > > also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }
> > > With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.
> > 
> > 
> > Thanks, I am already started working on it. @bryantmero hope to upload to a branch when my beta version is ready
> 
> I have already started some homework, this steps I am following for conversion to Swift (Metal Graphics)
> 
> o some OpenGL cleanup. Follow these steps:
> 
>     1. Rename both occurrences of setupGL() to setupMetal().
> 
>     2. Remove tearDownGL() and deinit() methods. With Metal, there’s no need for explicit cleanup like this.
> 
>     3. Find and remove the whole extension GLKViewControllerDelegate, since this view controller is no longer a GLKViewController. Note that glkViewControllerUpdate contains the logic for spinning. This is useful, but for now, remove it.
> 
>     4. Remove the following code from the top of setupMetal():
> 
> 
> context = EAGLContext(api: .openGLES3) EAGLContext.setCurrent(context)
> 
> if let view = self.view as? GLKView, let context = context { view.context = context delegate = self }
> 
>     5. Remove the following properties from the top of ViewController:
> 
> 
> private var context: EAGLContext? private var effect = GLKBaseEffect() private var ebo = GLuint() private var vbo = GLuint() private var vao = GLuint()
> 
> Finally, at the top of the ViewController class declaration, add an outlet to a MTKView:
> 
> @IBOutlet weak var metalView: MTKView!

Can I get your code? Me too also want to work on this

There is another Cover Flow project, here: https://github.com/vyarovyi/android_coverflow_gallery

But it is having issue with rotation @tanjinbd

**Comment by tanjinbd** [comment]
> > > > In the project root folder, go to: src\com\gpit\bd\liberation
> > > > Following Android Libraries are used: view.animation.Transformation android.graphics.Matrix
> > > > also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }
> > > > With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.
> > > 
> > > 
> > > Thanks, I am already started working on it. @bryantmero hope to upload to a branch when my beta version is ready
> > 
> > 
> > I have already started some homework, this steps I am following for conversion to Swift (Metal Graphics)
> > o some OpenGL cleanup. Follow these steps:
> > ```
> > 1. Rename both occurrences of setupGL() to setupMetal().
> > 
> > 2. Remove tearDownGL() and deinit() methods. With Metal, there’s no need for explicit cleanup like this.
> > 
> > 3. Find and remove the whole extension GLKViewControllerDelegate, since this view controller is no longer a GLKViewController. Note that glkViewControllerUpdate contains the logic for spinning. This is useful, but for now, remove it.
> > 
> > 4. Remove the following code from the top of setupMetal():
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > context = EAGLContext(api: .openGLES3) EAGLContext.setCurrent(context)
> > if let view = self.view as? GLKView, let context = context { view.context = context delegate = self }
> > ```
> > 5. Remove the following properties from the top of ViewController:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > private var context: EAGLContext? private var effect = GLKBaseEffect() private var ebo = GLuint() private var vbo = GLuint() private var vao = GLuint()
> > Finally, at the top of the ViewController class declaration, add an outlet to a MTKView:
> > @IBOutlet weak var metalView: MTKView!
> 
> Can I get your code? Me too also want to work on this
> 
> There is another Cover Flow project, here: https://github.com/vyarovyi/android_coverflow_gallery
> 
> But it is having issue with rotation @tanjinbd

Yes that can be used to, for IOS conversion

Also to convert OpenGL shaders to Metal, A readily library is available already:
 [MoltenGL](https://moltengl.com/moltengl/) 

@luismartinez03 , Can you please share your exception log so that, I can check why the app is crashing on your phone (Galaxy 9)

**Comment by bryantmero** [comment]
> > > > > In the project root folder, go to: src\com\gpit\bd\liberation
> > > > > Following Android Libraries are used: view.animation.Transformation android.graphics.Matrix
> > > > > also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }
> > > > > With effective use with View and Animation transformation, the desired result is achieved. Please let me know if you need any further help regarding this.
> > > > 
> > > > 
> > > > Thanks, I am already started working on it. @bryantmero hope to upload to a branch when my beta version is ready
> > > 
> > > 
> > > I have already started some homework, this steps I am following for conversion to Swift (Metal Graphics)
> > > o some OpenGL cleanup. Follow these steps:
> > > ```
> > > 1. Rename both occurrences of setupGL() to setupMetal().
> > > 
> > > 2. Remove tearDownGL() and deinit() methods. With Metal, there’s no need for explicit cleanup like this.
> > > 
> > > 3. Find and remove the whole extension GLKViewControllerDelegate, since this view controller is no longer a GLKViewController. Note that glkViewControllerUpdate contains the logic for spinning. This is useful, but for now, remove it.
> > > 
> > > 4. Remove the following code from the top of setupMetal():
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > context = EAGLContext(api: .openGLES3) EAGLContext.setCurrent(context)
> > > if let view = self.view as? GLKView, let context = context { view.context = context delegate = self }
> > > ```
> > > 5. Remove the following properties from the top of ViewController:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > private var context: EAGLContext? private var effect = GLKBaseEffect() private var ebo = GLuint() private var vbo = GLuint() private var vao = GLuint()
> > > Finally, at the top of the ViewController class declaration, add an outlet to a MTKView:
> > > @IBOutlet weak var metalView: MTKView!
> > 
> > 
> > Can I get your code? Me too also want to work on this
> > There is another Cover Flow project, here: https://github.com/vyarovyi/android_coverflow_gallery
> > But it is having issue with rotation @tanjinbd
> 
> Yes that can be used to, for IOS conversion
> 
> Also to convert OpenGL shaders to Metal, A readily library is available already: [MoltenGL](https://moltengl.com/moltengl/)
> 
> @luismartinez03 , Can you please share your exception log so that, I can check why the app is crashing on your phone (Galaxy 9)

@tanjinbd :

Below is the exception log:
Uncaught handler: thread main exiting due to uncaught exception
 21:35:15.397: ERROR/AndroidRuntime(253): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dazlious.android.helloworld/com.dazlious.android.helloworld.main}: java.lang.ArrayIndexOutOfBoundsException
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268) 
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.app.ActivityThread.access$1800(ActivityThread.java:112)
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.os.Handler.dispatchMessage(Handler.java:99)
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.os.Looper.loop(Looper.java:123)
 21:35:15.397: ERROR/AndroidRuntime(253):     at android.app.ActivityThread.main(ActivityThread.java:3948)
 21:35:15.397: ERROR/AndroidRuntime(253):     at java.lang.reflect.Method.invokeNative(Native Method)
 21:35:15.397: ERROR/AndroidRuntime(253):     at java.lang.reflect.Method.invoke

**Comment by tanjinbd** [comment]
@bryantmero & @luismartinez03 I have updated the code handle this exception, so far I have checked with several physical handsets; did not notice any crashing or other issues. Please verify and confirm from your end.

**Comment by bryantmero** [comment]
@tanjinbd , thanks I have checked, its working now

**Comment by bryantmero** [comment]
I have used below code:
also check transformImageBitmap() class: if ( rotation < mMaxRotationAngle ) { float zoomAmount = (float) (mMaxZoom + (rotation * 1.5)); mCamera.translate(0.0f, 0.0f, zoomAmount); }

And changed rotation to 2.0; (it makes the rendering cooler), but running for 5+ mins on my screen the animation quality gets low
@tanjinbd any observation?

My Phone: Samsung A8

**Comment by tanjinbd** [comment]
@bryantmero , can you please provide me a screenshot (Highlighting the quality issue)

**Comment by RummanUK** [comment]
![low](https://user-images.githubusercontent.com/107975951/181413344-ba973025-58e9-480f-a9fb-548738e0e32c.jpg)
Here is, check the image is having pixels

**Comment by tanjinbd** [comment]
Try using following parameter in following function:
new LibWarCoverFlow.Builder()
             .with(viewpager)
             .pagerMargin(0f)
             **.scale(0.9f)**
             .spaceSize(0f)
             .rotationY(0f)
             .build();

If you create a function that inherits the HDPI scaling from your phone it will be fullproof how much scaling the scene (object) needs to be rendered

**Comment by bryantmero** [comment]
> Try using following parameter in following function: new LibWarCoverFlow.Builder() .with(viewpager) .pagerMargin(0f) **.scale(0.9f)** .spaceSize(0f) .rotationY(0f) .build();
> 
> If you create a function that inherits the HDPI scaling from your phone it will be fullproof how much scaling the scene (object) needs to be rendered

Thanks a ton @tanjinbd , it really helped me to uitilize the code on my project +++
